module Monopoly
  class MonopolyBoard < Game::GameBoard

    def initialize(monopoly)
      super(monopoly)

      # Create Cities
      onsdorp   = PropertyGroup.new("Ons Dorp")
      arnhem    = PropertyGroup.new("Arnhem")
      haarlem   = PropertyGroup.new("Haarlem")
      utrecht   = PropertyGroup.new("Utrecht")
      groningen = PropertyGroup.new("Groningen")
      denhaag   = PropertyGroup.new("Den Haag")
      rotterdam = PropertyGroup.new("Rotterdam")
      amsterdam = PropertyGroup.new("Amsterdam")

      # Create streets
      dorpstraat        = Space::Street.new(@boardgame, onsdorp, "Dorpstraat", 10, 2)
      brink             = Space::Street.new(@boardgame, onsdorp, "Brink", 15, 2)
      steenstraat       = Space::Street.new(@boardgame, arnhem, "Steenstraat", 20, 3)
      ketelstraat       = Space::Street.new(@boardgame, arnhem, "Ketelstraat", 25, 3)
      velperplein       = Space::Street.new(@boardgame, arnhem, "Velperplein", 30, 3)
      barteljorisstraat = Space::Street.new(@boardgame, haarlem, "Barteljorisstraat", 35, 4)
      zijlweg           = Space::Street.new(@boardgame, haarlem, "Zijlweg", 40, 4)
      houtstraat        = Space::Street.new(@boardgame, haarlem, "Houtstraat", 45, 4)
      neude             = Space::Street.new(@boardgame, utrecht, "Neude", 50, 5)
      bilstraat         = Space::Street.new(@boardgame, utrecht, "Biltstraat", 55, 5)
      vreeburg          = Space::Street.new(@boardgame, utrecht, "Vreeburg", 60, 5)
      akerkhof          = Space::Street.new(@boardgame, groningen, "A Kerkhof", 65, 6)
      grotemarkt        = Space::Street.new(@boardgame, groningen, "Grote Markt", 70, 6)
      heerestraat       = Space::Street.new(@boardgame, groningen, "Heerestraat", 75, 6)
      spui              = Space::Street.new(@boardgame, denhaag, "Spui", 80, 7)
      plein             = Space::Street.new(@boardgame, denhaag, "Plein", 85, 7)
      langepoten        = Space::Street.new(@boardgame, denhaag, "Lange Poten", 90, 7)
      hofplein          = Space::Street.new(@boardgame, rotterdam, "Hofplein", 95, 8)
      blaak             = Space::Street.new(@boardgame, rotterdam, "Blaak", 100, 8)
      coolsingel        = Space::Street.new(@boardgame, rotterdam, "Coolsingel", 105, 8)
      leidschestraat    = Space::Street.new(@boardgame, amsterdam, "Leidschestraat", 110, 9)
      kalverstraat      = Space::Street.new(@boardgame, amsterdam, "Kalverstraat", 115, 10)

      # Adding streets to cities
      onsdorp.add_property(dorpstraat)
      onsdorp.add_property(brink)
      arnhem.add_property(steenstraat)
      arnhem.add_property(ketelstraat)
      arnhem.add_property(velperplein)
      haarlem.add_property(barteljorisstraat)
      haarlem.add_property(zijlweg)
      haarlem.add_property(houtstraat)
      utrecht.add_property(neude)
      utrecht.add_property(bilstraat)
      utrecht.add_property(vreeburg)
      groningen.add_property(akerkhof)
      groningen.add_property(grotemarkt)
      groningen.add_property(heerestraat)
      denhaag.add_property(spui)
      denhaag.add_property(plein)
      denhaag.add_property(langepoten)
      rotterdam.add_property(hofplein)
      rotterdam.add_property(blaak)
      rotterdam.add_property(coolsingel)
      amsterdam.add_property(leidschestraat)
      amsterdam.add_property(kalverstraat)

      # Create Train Stations
      stations = PropertyGroup.new("Stations")
      station_south = Space::Station.new(@boardgame, stations, "station south")
      station_west  = Space::Station.new(@boardgame, stations, "station west")
      station_north = Space::Station.new(@boardgame, stations, "station north")
      station_east  = Space::Station.new(@boardgame, stations, "station east")

      # Create Utilities
      utilities = PropertyGroup.new("utilities")
      electric = Space::Utility.new(@boardgame, utilities, "electric utility")
      water    = Space::Utility.new(@boardgame, utilities, "water utility")

      # Add spaces
      add_space(Space::Start.new(@boardgame))
      add_space(dorpstraat)
      add_space(Game::Space.new(@boardgame, "fonds"))
      add_space(brink)
      add_space(Space::Tax.new(@boardgame, "incometax", 200))
      add_space(station_south)
      add_space(steenstraat)
      add_space(Game::Space.new(@boardgame, "kans"))
      add_space(ketelstraat)
      add_space(velperplein)
      add_space(Game::Space.new(@boardgame, "gevaningenis"))
      add_space(barteljorisstraat)
      add_space(electric)
      add_space(zijlweg)
      add_space(houtstraat)
      add_space(station_west)
      add_space(neude)
      add_space(Game::Space.new(@boardgame, "fonds"))
      add_space(bilstraat)
      add_space(vreeburg)
      add_space(Space::FreeParking.new(@boardgame))
      add_space(akerkhof)
      add_space(Game::Space.new(@boardgame, "kans"))
      add_space(grotemarkt)
      add_space(heerestraat)
      add_space(station_north)
      add_space(spui)
      add_space(plein)
      add_space(water)
      add_space(langepoten)
      add_space(Game::Space.new(@boardgame, "to yail"))
      add_space(hofplein)
      add_space(blaak)
      add_space(Game::Space.new(@boardgame, "fonds"))
      add_space(coolsingel)
      add_space(station_east)
      add_space(Game::Space.new(@boardgame, "kans"))
      add_space(leidschestraat)
      add_space(Space::Tax.new(@boardgame, "luxurytax", 100))
      add_space(kalverstraat)
    end
  end
end