require 'game/boardgame'
require 'game/dice'
require 'game/die'
require 'game/duotraditionaldice'
require 'game/gameboard'
require 'game/player'
require 'game/settings'
require 'game/traditionaldie'

require 'game/space/space'
require 'game/space/space_action'

require 'game/space/action/condition/satisfiable'
require 'game/space/action/condition/condition'
require 'game/space/action/condition/chain'
require 'game/space/action/condition/always'
require 'game/space/action/condition/ontargetposition'
require 'game/space/action/condition/onstartposition'
require 'game/space/action/condition/onpassposition'

require 'game/space/action/executor'

require 'monopoly/player'
require 'monopoly/monopoly'
require 'monopoly/monopolyboard'
require 'monopoly/pot'
require 'monopoly/settings'

require 'monopoly/space/space'

require 'monopoly/space/property/property'
require 'monopoly/space/property/propertygroup'
require 'monopoly/space/property/prisonerproperty'
require 'monopoly/space/property/propertydecorator'
require 'monopoly/space/property/propertywithadditionalrent'

require 'monopoly/space/start'
require 'monopoly/space/tax'
require 'monopoly/space/freeparking'
require 'monopoly/space/street'
require 'monopoly/space/station'
require 'monopoly/space/utility'
require 'monopoly/space/jail'
require 'monopoly/space/gotojail'
require 'monopoly/space/additionalrent'