require 'game/die'
require 'game/face'
require 'game/dice'
require 'game/boardgame'
require 'game/gameboard'
require 'game/player'
require 'game/space'
require 'game/settings'

require 'monopoly/monopoly'
require 'monopoly/monopolyboard'
require 'monopoly/traditionaldie'
require 'monopoly/monopolyspace'
require 'monopoly/startspace'
require 'monopoly/freeparkingspace'
require 'monopoly/incometaxspace'
require 'monopoly/luxurytaxspace'
require 'monopoly/pot'


